Add suggestion of awsprofile alias for easier profile switching to RE…
techservicesillinois/awscli-login pull request #200
Opened 2024-08-16 20:07 UTC by kwessel

…ADME

2024-08-20 17:08 UTC, ddriddle requested changes
@kwessel Thank you very much for the PR! I made some suggestions to make the alias compatible with any Bourne shell. I also testesd it with bash, zsh, ksh, and dash as it stands it is not compatible with shells other than zsh but with a minor tweak it works on them all! Please take a look at the changes and approve them or make changes as needed. Thanks!

2024-08-20 17:08 UTC, ddriddle commented on docs/readme/body.rst
> +commands to use:
```suggestion
This function should work on any Bourne compatible shell (bash, zsh, ksh, dash, etc). 
Using this function, you can set the profile for the aws login and other aws commands to use:
```

2024-08-20 17:08 UTC, ddriddle commented on docs/readme/body.rst
> +profile is selected.
Note that if AWS_PROFILE is clear the default profile is automatically selected. I found the last part of the sentence a little confusing so I shortened it.

```suggestion
awsprofile commands. Additionally, you can run awsprofile without any
profile name to clear $AWS_PROFILE.
```

2024-08-23 15:28 UTC, ddriddle approved these changes

2024-08-23 15:40 UTC, tzturner approved these changes

2024-08-23 16:50 UTC, merged